namespace: daniel-lopez-fisag-dev

frontend:
  image: danielopezh/comments-frontend
  tag: 3
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

backendApi:
  image: danielopezh/comments-backend-api
  tag: 2
  replicas: 1
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 5

backendData:
  image: danielopezh/comments-backend-data
  tag: 2
  replicas: 1
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

database:
  image: danielopezh/comments-database
  tag: 2
  storage: 1Gi
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
