namespace: daniel-lopez-fisag-dev

frontend:
  image: danielopezh/comments-frontend
  tag: 2
  replicas: 1

backendApi:
  image: danielopezh/comments-backend-api
  tag: 2
  replicas: 1

backendData:
  image: danielopezh/comments-backend-data
  tag: 2
  replicas: 1

database:
  image: danielopezh/comments-database
  tag: 2
  storage: 1Gi
