apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: {{ .Values.namespace }}
  labels:
    app: backend-api
spec:
  replicas: {{ .Values.backendApi.replicas }}
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: {{ .Values.backendApi.image }}:{{ .Values.backendApi.tag }}
        ports:
        - containerPort: 3000
        env:
        - name: DATA_SERVICE_URL
          value: "http://backend-data-service:3001"
        resources:
          requests:
            cpu: {{ .Values.backendApi.resources.requests.cpu }}
            memory: {{ .Values.backendApi.resources.requests.memory }}
          limits:
            cpu: {{ .Values.backendApi.resources.limits.cpu }}
            memory: {{ .Values.backendApi.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
